# BASE_DATA_DIR = "../anonymizer/anonymized"
BASE_DATA_DIR = "../data"

EMA = False
IMAGE_SIZE = (224, 224)
NORM_MEAN = 0.5
NORM_STD = 0.5

TRAIN_SIZE = 0.7
VAL_SIZE = 1 - TRAIN_SIZE

EPOCHS = 100
BATCH_SIZE = 32
LR = 1e-4
LR_FACTOR = 0.2
WEIGHT_DECAY = 1e-4
LR_PATIENCE = 10
EARLY_STOP_EPOCHS = 30
