BASE_DATA_DIR = "../anonymizer/anonymized"

EMA = False
IMAGE_SIZE = (224, 224)

TRAIN_SIZE = 0.7
VAL_SIZE = 1 - TRAIN_SIZE

EPOCHS = 100
BATCH_SIZE = 64
LR = 1e-4
LR_FACTOR = 0.2
WEIGHT_DECAY = 1e-4
LR_PATIENCE = 10
EARLY_STOP_EPOCHS = 30
